---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Updating the current compose file
    replace:
      path: /home/ec2-user/yuvraj/docker-compose.yml
      regexp: 'vaibhavrajnathchauhan\/event-ticket-booking-system:*(.+)$'
      replace: "vaibhavrajnathchauhan/event-ticket-booking-system:{{ BUILD_ID }}"

  # docker compose up
  - name: Running the container
    docker_compose:
      project_src: /home/ec2-user/yuvraj
      build: false
      restarted: true